schema = "avalon-core:inventory-1.0"


# project settings
root = "O:"
renderRoot = ""
standinRoot = ""
codename = ""
resolution_width = 1920
resolution_height = 1080
stereo = false
fps = 30
fpses = []
handles = 1
edit_in = 101
edit_out = 200

[role]
admin = [
]
member = [
]

[pipeline]
[pipeline.maya]
turntable = "LookDevStage"

[workspace]
[[workspace.apps]]
schema = "avalon-core:application-1.0"
name = "maya"
label = "Autodesk Maya"
executable = "maya"
application_dir = "maya"
default_dirs = [
	"scenes",
	"data",
	"renderData/shaders",
	"images"
]
[workspace.apps.copy]
"{CONFIG_ROOT}/res/maya/workspace.mel" = "workspace.mel"

[[workspace.apps]]
schema = "avalon-core:application-1.0"
name = "nuke"
label = "Nuke"
executable = "nuke"
application_dir = "nuke"
default_dirs = [
	"precomps",
	"renders"
]

[[workspace.apps]]
schema = "avalon-core:application-1.0"
name = "houdini"
label = "Houdini"
executable = "houdini"
application_dir = "houdini"
default_dirs = [
	"scenes",
	"data",
	"renders"
]
